// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static final FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDgxm0RxWexg93gRtYyvrC-3JRkpsE62bw',
//     appId: '1:299727334191:web:71013f030dc57202838fda',
//     messagingSenderId: '299727334191',
//     projectId: 'elephant-tracking-mobile-app',
//     authDomain: 'elephant-tracking-mobile-app.firebaseapp.com',
//     storageBucket: 'elephant-tracking-mobile-app.firebasestorage.app',
//   );
//
//   static final FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDGZwb55J698YK1TfEKAUoOuNg6DxhdWzw',
//     appId: '1:299727334191:ios:92525b704f6f6774838fda',
//     messagingSenderId: '299727334191',
//     projectId: 'elephant-tracking-mobile-app',
//     storageBucket: 'elephant-tracking-mobile-app.firebasestorage.app',
//     iosBundleId: 'com.example.elephantTrackingMobileApp',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyA90KshuePJIW_FxbgfrZ_2bzWd_mhpCqY',
//     appId: '1:482826830556:ios:6757a6749e9d487acd6a19',
//     messagingSenderId: '482826830556',
//     projectId: 'elephanttrackerapp',
//     storageBucket: 'elephanttrackerapp.firebasestorage.app',
//     iosBundleId: 'com.example.elephantTrackingMobileApp',
//   );
//
//   static final FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDZFdJ3w9HnNew-4A5mzt4doYnb_VisMLI',
//     appId: '1:482826830556:web:61e64bfc4342d2d9cd6a19',
//     messagingSenderId: '482826830556',
//     projectId: 'elephanttrackerapp',
//     authDomain: 'elephanttrackerapp.firebaseapp.com',
//     storageBucket: 'elephanttrackerapp.firebasestorage.app',
//     measurementId: 'G-F5MB7G5X2Q',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBfL8QY0QeGSayfzoB9pdFbTorCXPglpuA',
//     appId: '1:299727334191:android:86db96bca278ea3c838fda',
//     messagingSenderId: '299727334191',
//     projectId: 'elephant-tracking-mobile-app',
//     storageBucket: 'elephant-tracking-mobile-app.firebasestorage.app',
//   );
//
// }